---
- hosts: all
  become: yes
  become_user: root
  roles:
    - bootstrap

- hosts: ruby_rvm
  become: yes
  become_user: root
  roles:
    - ruby-rvm

- hosts: nodesource_nodejs
  become: yes
  become_user: root
  roles:
    - nodesource-nodejs
